### ISSUE TITLE
Failed to compile. issue

### ISSUE THREAD

**Issue by guys1444** [vitordino/movies#15]
**hi getting an error ..

any suggestion?

![image](https://user-images.githubusercontent.com/32614636/103141907-3a63ea80-4704-11eb-97c5-ec31236f737d.png)

**Comment by guys1444** [comment]
Failed to compile.

./src/index.js
SyntaxError: C:\guy\movies\movies\src\index.js: Unexpected token (14:1)

  12 |
  13 | const Wrapper = () => (
> 14 |  <ThemeProvider theme={theme}>
     |  ^
  15 |          <GridProvider columns={theme.columns} breakpoints={theme.breakpoints}>
  16 |                  <FavoritesProvider>
  17 |                          <App/>

**Comment by vitordino** [comment]
hi there 👋 

the error is pointing to a `syntax error` on a **jsx** expression, you probably are trying to run this on an environment that doesn’t understand it — like a node server without babel configured properly.

have you tried installing the dependencies and running the app following the readme development guide? how did you try running this?

**Comment by vitordino** [comment]
feel free to reopen if you still need assistance with this
